#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Fri Nov  4 19:17:15 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class nftFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: nftFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((452, 389))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        nftImage = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("/home/developer/src/xrpl-cli/testimage.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(nftImage, 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class nftFrame

class nftSniffer(wx.App):
    def OnInit(self):
        self.frame = nftFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class nftSniffer

if __name__ == "__main__":
    nftSniffer = nftSniffer(0)
    nftSniffer.MainLoop()
